name: shelf_docker_shutdown
description: Close the HttpServer on process TERM signals.
version: 1.0.0
homepage: https://github.com/kkazuo/shelf_docker_shutdown

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   shelf:

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^3.1.0
