name: shelf_docker_shutdown
description: Close the HttpServer on process TERM signals.
version: 1.1.0
homepage: https://github.com/kkazuo/shelf_docker_shutdown

environment:
  sdk: '>=3.6.0 <4.0.0'

# dependencies:
#   shelf:

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
